"""add owner credits, credit applications, and charge late fee link

Revision ID: 18b94f290fa6
Revises: cbaa7a3c01f9
Create Date: 2026-09-03 15:02:51.665204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b94f290fa6'
down_revision = 'cbaa7a3c01f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['source_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_credits_id'), 'owner_credits', ['id'], unique=False)
    op.create_index(op.f('ix_owner_credits_organization_id'), 'owner_credits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_owner_credits_owner_id'), 'owner_credits', ['owner_id'], unique=False)
    op.create_table('credit_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['credit_id'], ['owner_credits.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_applications_charge_id'), 'credit_applications', ['charge_id'], unique=False)
    op.create_index(op.f('ix_credit_applications_credit_id'), 'credit_applications', ['credit_id'], unique=False)
    op.create_index(op.f('ix_credit_applications_id'), 'credit_applications', ['id'], unique=False)
    op.create_index(op.f('ix_credit_applications_organization_id'), 'credit_applications', ['organization_id'], unique=False)
    op.add_column('charges', sa.Column('related_charge_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('charges') as batch_op:
        batch_op.create_foreign_key('fk_charges_related_charge_id', 'charges', ['related_charge_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges') as batch_op:
        batch_op.drop_constraint('fk_charges_related_charge_id', type_='foreignkey')
    op.drop_column('charges', 'related_charge_id')
    op.drop_index(op.f('ix_credit_applications_organization_id'), table_name='credit_applications')
    op.drop_index(op.f('ix_credit_applications_id'), table_name='credit_applications')
    op.drop_index(op.f('ix_credit_applications_credit_id'), table_name='credit_applications')
    op.drop_index(op.f('ix_credit_applications_charge_id'), table_name='credit_applications')
    op.drop_table('credit_applications')
    op.drop_index(op.f('ix_owner_credits_owner_id'), table_name='owner_credits')
    op.drop_index(op.f('ix_owner_credits_organization_id'), table_name='owner_credits')
    op.drop_index(op.f('ix_owner_credits_id'), table_name='owner_credits')
    op.drop_table('owner_credits')
    # ### end Alembic commands ###
