"""add vendors table

Revision ID: 204051e25c6e
Revises: 9767b1f06c47
Create Date: 2026-09-03 18:50:16.545981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204051e25c6e'
down_revision = '9767b1f06c47'
branch_labels = None
depends_on = None

vendor_category_enum = sa.Enum(
    'MANTENIMIENTO', 'SEGURIDAD', 'LIMPIEZA', 'JARDINERIA', 'PLOMERIA', 'ELECTRICIDAD', 'OTRO',
    name='vendorcategory',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('MANTENIMIENTO', 'SEGURIDAD', 'LIMPIEZA', 'JARDINERIA', 'PLOMERIA', 'ELECTRICIDAD', 'OTRO', name='vendorcategory'), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_organization_id'), 'vendors', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_organization_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
    vendor_category_enum.drop(op.get_bind(), checkfirst=True)
