"""add org_type, tax_id, contact fields to organizations

Revision ID: 7b1bf7e3c5ac
Revises: dcf10b9dd9e8
Create Date: 2026-09-02 22:28:38.814169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1bf7e3c5ac'
down_revision = 'dcf10b9dd9e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('org_type', sa.Enum('RESIDENCIAL', 'CORPORATIVO', 'PARCELAS', 'ADMINISTRADORA', name='organizationtype'), nullable=True))
    op.add_column('organizations', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'tax_id')
    op.drop_column('organizations', 'org_type')
    # ### end Alembic commands ###
