"""add payment receipt_number and property photo_url

Revision ID: 9767b1f06c47
Revises: 18b94f290fa6
Create Date: 2026-09-03 15:56:15.074969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9767b1f06c47'
down_revision = '18b94f290fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_receipt_number'), 'payments', ['receipt_number'], unique=False)
    op.add_column('properties', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'photo_url')
    op.drop_index(op.f('ix_payments_receipt_number'), table_name='payments')
    op.drop_column('payments', 'receipt_number')
    # ### end Alembic commands ###
