"""add units table

Revision ID: a857dd5a3036
Revises: ce9158494f8e
Create Date: 2026-09-03 12:05:46.348732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a857dd5a3036'
down_revision = 'ce9158494f8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('unit_type', sa.Enum('DEPARTAMENTO', 'OFICINA', 'BODEGA', 'ESTACIONAMIENTO', 'LOCAL_COMERCIAL', name='unittype'), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
