"""add finance tables (charges, payments, payment_applications)

Revision ID: cbaa7a3c01f9
Revises: ede3d7a080a9
Create Date: 2026-09-03 14:20:23.863523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaa7a3c01f9'
down_revision = 'ede3d7a080a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', name='chargestatus'), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_id'), 'charges', ['id'], unique=False)
    op.create_index(op.f('ix_charges_organization_id'), 'charges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_charges_unit_id'), 'charges', ['unit_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_unit_id'), 'payments', ['unit_id'], unique=False)
    op.create_table('payment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_applications_charge_id'), 'payment_applications', ['charge_id'], unique=False)
    op.create_index(op.f('ix_payment_applications_id'), 'payment_applications', ['id'], unique=False)
    op.create_index(op.f('ix_payment_applications_organization_id'), 'payment_applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payment_applications_payment_id'), 'payment_applications', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_applications_payment_id'), table_name='payment_applications')
    op.drop_index(op.f('ix_payment_applications_organization_id'), table_name='payment_applications')
    op.drop_index(op.f('ix_payment_applications_id'), table_name='payment_applications')
    op.drop_index(op.f('ix_payment_applications_charge_id'), table_name='payment_applications')
    op.drop_table('payment_applications')
    op.drop_index(op.f('ix_payments_unit_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_charges_unit_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_organization_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_id'), table_name='charges')
    op.drop_table('charges')
    # ### end Alembic commands ###
