"""add owners and unit_owners tables

Revision ID: ede3d7a080a9
Revises: a857dd5a3036
Create Date: 2026-09-03 13:45:24.438252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede3d7a080a9'
down_revision = 'a857dd5a3036'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('identification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_organization_id'), 'owners', ['organization_id'], unique=False)
    op.create_table('unit_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_owners_id'), 'unit_owners', ['id'], unique=False)
    op.create_index(op.f('ix_unit_owners_organization_id'), 'unit_owners', ['organization_id'], unique=False)
    op.create_index(op.f('ix_unit_owners_owner_id'), 'unit_owners', ['owner_id'], unique=False)
    op.create_index(op.f('ix_unit_owners_unit_id'), 'unit_owners', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_owners_unit_id'), table_name='unit_owners')
    op.drop_index(op.f('ix_unit_owners_owner_id'), table_name='unit_owners')
    op.drop_index(op.f('ix_unit_owners_organization_id'), table_name='unit_owners')
    op.drop_index(op.f('ix_unit_owners_id'), table_name='unit_owners')
    op.drop_table('unit_owners')
    op.drop_index(op.f('ix_owners_organization_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
